export const requests = {
  login: "/auth/login",
  signup: "/auth/signup",
  check: "/auth/check",
  logout: "/auth/logout",
  sendOTP: "/auth/sendOTP",
  change_password: "/auth/change_password",
  createTweets: "/tweets/create",
  getTweets: "/tweets",
  getFollowedTweets: "/tweets/followed",
  likeTweet: "/tweets/like",
  retweetTweet: "/tweets/retweet",
  bookmarkTweet: "/tweets/bookmark",
  replyTweet: "/tweets/reply",
  changeUsername: "/profile/changeUsername",
  userPreferences: "/auth/user_preferences",
};
